### ISSUE TITLE
Fix Energy Display

### ISSUE THREAD

**Issue by HaedHutner** [Atherys-Horizons/AtherysSkills#12]
**Description:** When entering/exiting a battle point, when the player is regenerating energy, every time the energy amount is updated, the "Entering Battlepoint..." subtitle is displayed

**Reproduction Steps:** While regenerating energy, enter/exit a battle point

**Expected Behavior:** The energy display should be updated independently from the enter/exit battle point subtitle

**Observed Behavior:** See Description

**Comment by fingoltin** [comment]
I'm not sure the best way to go about this. Resetting the player's title before displaying energy would probably result in clearing other titles preemptively. Resetting the title *after* displaying another title would be preferable, but much harder. There also does not seem to be a way to retrieve the player's current title.
